[package]
name = "qdrant"
version = "1.1.0"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "web", "parking_lot" ]
web = ["actix-web"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]

[dev-dependencies]
serde_urlencoded = "0.7"

tempfile = "3.4.0"
rusty-hook = "^0.11.2"


[dependencies]

parking_lot = { version = "0.12.1", features=["deadlock_detection"], optional = true }

num_cpus = "1.15"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10.0"
atty = "0.2"
colored = "2"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
chrono = { version = "~0.4", features = ["serde"] }
schemars = { version = "0.8.12", features = ["uuid1", "preserve_order", "chrono"] }
itertools = "0.10"
anyhow = "1.0.69"
futures = "0.3.27"
futures-util = "0.3.27"
clap = { version = "4.1.8", features = ["derive"] }
serde_cbor = { version = "0.11.2"}
uuid = { version = "1.3", features = ["v4", "serde"] }
sys-info = "0.9.1"

config = "~0.13.3"

tokio = { version = "~1.26", features = ["full"] }

actix-web = { version = "4.3.1", optional = true }
actix-cors = "0.6.4"
actix-files = "0.6.2"
tonic = { version = "0.8.3", features = ["gzip"] }
tower = "0.4.13"
tower-layer = "0.3.2"
num-traits = "0.2.15"
tar = "0.4.38"
reqwest = { version = "0.11", features = ["stream", "rustls-tls", "blocking"] }
openssl = { version = "0.10", features = ["vendored"] }
prometheus = { version = "0.13.3", default-features = false }

# Consensus related crates
raft = { git = "https://github.com/tikv/raft-rs", rev = "5ce52b480065ff31ecef16b9b77c7c3b7c57c8c7", features = ["prost-codec"], default-features = false }
slog = "2.7.0"
slog-stdlog = "4.1.1"
prost = "0.11.8"
raft-proto = {  git = "https://github.com/tikv/raft-rs", rev = "5ce52b480065ff31ecef16b9b77c7c3b7c57c8c7", features = ["prost-codec"], default-features = false}

segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }
api = { path = "lib/api" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
exclude = ["benches/search-points"]

[profile.release]
lto = "fat"